### ISSUE TITLE
模拟结果当中，存在审批时间错误，请问如何修改

### ISSUE THREAD

**Issue by MrSu0215** [uiolee/BuZaiXiaoYuan#2]
审批时间能否修改为当日开始时间前1小时，仓库中的getLeave.js，我没有进行修改，可以完美使用，唯独审批时间的生成，出现错误。请问该如何修改？

![微信图片_20220913172641](https://user-images.githubusercontent.com/55876369/189865200-5d523865-aea3-4c1e-a572-049c99494e88.jpg)

**Comment by uiolee** [comment]
getLeave.js#L89

**Comment by MrSu0215** [comment]
> 

现在辅导员审核时间正常，院级审核时间，没办法模拟，怎么办
